// Generated from content/content.md — Review Kanji Practice, 51 items.
export const cards = [
  { reading: "さかな", written: "魚", meaning: "fish" },
  { reading: "わける", written: "分ける", meaning: "to divide" },
  { reading: "きょう", written: "今日", meaning: "today" },
  { reading: "ぜんぶ", written: "全ぶ〔全部〕", meaning: "all" },
  { reading: "らいげつ", written: "来月", meaning: "next month" },
  { reading: "ふっどさん", written: "フッド山", meaning: "Mt. Hood" },
  { reading: "すいようび", written: "水曜日", meaning: "Wednesday" },
  { reading: "とり", written: "鳥", meaning: "bird" },
  { reading: "ゆうしょく", written: "夕食", meaning: "dinner" },
  { reading: "じょうず", written: "上手", meaning: "skilled / good at" },
  { reading: "さくぶん", written: "作文", meaning: "composition" },
  { reading: "まいにち", written: "毎日", meaning: "every day" },
  { reading: "でんしゃ", written: "電車", meaning: "train" },
  { reading: "ごふん", written: "五分", meaning: "five minutes" },
  { reading: "ほそい", written: "細い", meaning: "thin / narrow" },
  { reading: "おおい", written: "多い", meaning: "many" },
  { reading: "にほんじん", written: "日本人", meaning: "Japanese person" },
  { reading: "こない", written: "来ない", meaning: "won't come" },
  { reading: "ふとい", written: "太い", meaning: "thick / fat" },
  { reading: "ぶんすう", written: "分すう〔分数〕", meaning: "fraction" },
  { reading: "だいけい", written: "台形", meaning: "trapezoid" },
  { reading: "ことば", written: "言ば〔言葉〕", meaning: "word" },
  { reading: "はんぶん", written: "半分", meaning: "half" },
  { reading: "せんせい", written: "先生", meaning: "teacher" },
  { reading: "くる", written: "来る", meaning: "to come" },
  { reading: "なにぐみ", written: "何組", meaning: "which class/group" },
  { reading: "だいすき", written: "大好き", meaning: "to love / really like" },
  { reading: "みょうじ", written: "名字", meaning: "surname" },
  { reading: "きる", written: "切る", meaning: "to cut" },
  { reading: "くに", written: "国", meaning: "country" },
  { reading: "つくる", written: "作る", meaning: "to make" },
  { reading: "だす", written: "出す", meaning: "to take out / submit" },
  { reading: "きょうりょく", written: "きょう力〔協力〕", meaning: "cooperation" },
  { reading: "りょうほう", written: "りょう方〔両方〕", meaning: "both" },
  { reading: "ちゅうごく", written: "中国", meaning: "China" },
  { reading: "やすみ", written: "休み", meaning: "rest / break" },
  { reading: "きゅうしょく", written: "きゅう食〔給食〕", meaning: "school lunch" },
  { reading: "まなぶ", written: "学ぶ", meaning: "to learn" },
  { reading: "いく", written: "行く", meaning: "to go" },
  { reading: "うみ", written: "海", meaning: "sea" },
  { reading: "たべる", written: "食べる", meaning: "to eat" },
  { reading: "みる", written: "見る", meaning: "to see / look" },
  { reading: "がっこう", written: "学校", meaning: "school" },
  { reading: "たいせつ", written: "大切", meaning: "important" },
  { reading: "むいか", written: "六日", meaning: "sixth (day)" },
  { reading: "おなじ", written: "同じ", meaning: "same" },
  { reading: "がいこく", written: "外国", meaning: "foreign country" },
  { reading: "せいほうけい", written: "正方形", meaning: "square" },
  { reading: "いう", written: "言う", meaning: "to say" },
  { reading: "しゃかい", written: "社会", meaning: "society" },
  { reading: "きたとみなみ", written: "北と南", meaning: "north and south" },
]
